POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "username": "kiet",
    "password": "1234"
}

###
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "username": "kiet99",
    "password": "1111"
}

###
POST http://localhost:5000/api/cities
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzlkZTIwZTRlZGI4NTgxMzg0MGM5ZDQiLCJpYXQiOjE2NzUzMjY4ODV9.88NwIBO5NWBL1ahl3-wyOtuTQTv1zUw3Y1OZNTU_STI

{
    "lat": "999",
    "lon": "112"
}

###
DELETE  http://localhost:5000/api/cities/63db330c3362a331afa15b49
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzlkZTIwZTRlZGI4NTgxMzg0MGM5ZDQiLCJpYXQiOjE2NzUzMTAwNDB9.sAAKtJ0goC5mFgLgcYGjBvj8cC8NqMlWnrCeOVCisac
